Add babel-jest
dilanx/craco pull request #532
Opened 2023-12-11 19:04 UTC by curtvict

Closes https://github.com/dilanx/craco/issues/531

2023-12-12 05:22 UTC, dilanx requested changes
Good catch! This change would need to be made in [`packages/craco/package.json`](https://github.com/dilanx/craco/blob/main/packages/craco/package.json) instead but once done I can include this fix in the upcoming update.

2023-12-12 17:08 UTC, curtvict commented
Thanks for the guidance @dilanx. This should be the right spot now?

2023-12-29 00:50 UTC, dilanx approved these changes

2023-12-29 00:51 UTC, dilanx commented
Looks good!

2023-12-29 01:00 UTC, merged